---
apiVersion: v1
kind: Service
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: validating-admission 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  replicas: 1
  template:
    metadata:
      name: validating-admission 
      labels:
        name: validating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/validating-admission:1.0.0
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 00Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: validating-admission
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-admission
webhooks:
  - name: validating-admission.qaware.de
    clientConfig:
      service:
        name: validating-admission
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVvQ0NRRHFwcnBUY1AzQVd6QU5CZ2txaGtpRzl3MEJBUTBGQURDQndqRUxNQWtHQTFVRUJoTUMKUkVVeEVEQU9CZ05WQkFnTUIwSmhkbUZ5YVdFeEVqQVFCZ05WQkFjTUNWSnZjMlZ1YUdWcGJURU9NQXdHQTFVRQpFUXdGT0RNd01qSXhIakFjQmdOVkJBa01GVUp5dzRQQ3ZHTnJaVzV6ZEhKaHc0UENuMlVnTVRFVU1CSUdBMVVFCkNnd0xVVUYzWVhKbElFZHRZa2d4RGpBTUJnTlZCQXNNQlVkQ0xVMU1NUkl3RUFZRFZRUUREQWx4WVhkaGNtVXUKWkdVeEl6QWhCZ2txaGtpRzl3MEJDUUVXRkhGaGQyRnlaUzF2YzNOQWNXRjNZWEpsTG1SbE1CNFhEVEl4TURFeQpNakl3TkRBeE9Gb1hEVEl4TURJeU1USXdOREF4T0Zvd2djSXhDekFKQmdOVkJBWVRBa1JGTVJBd0RnWURWUVFJCkRBZENZWFpoY21saE1SSXdFQVlEVlFRSERBbFNiM05sYm1obGFXMHhEakFNQmdOVkJCRU1CVGd6TURJeU1SNHcKSEFZRFZRUUpEQlZDY3NPRHdyeGphMlZ1YzNSeVljT0R3cDlsSURFeEZEQVNCZ05WQkFvTUMxRkJkMkZ5WlNCSApiV0pJTVE0d0RBWURWUVFMREFWSFFpMU5UREVTTUJBR0ExVUVBd3dKY1dGM1lYSmxMbVJsTVNNd0lRWUpLb1pJCmh2Y05BUWtCRmhSeFlYZGhjbVV0YjNOelFIRmhkMkZ5WlM1a1pUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFOUnc5eUhKQ1lVNStXR1lpWmpsNFpYR1FMd0hoUzJ4Tytjb1VuZ3V2emRTc3UydQpsbHJNSm43aXJrbjUycDQwTjNhWjYrWkZGN3gxbmwzMUhHV3h1dHQ1V01ITWFYczJpeVhGcEhpZzczeHF3dDd4CmJaV3NiOWdYZVRZaXRxRnBiTmE5OHFGbFlYTW1FdzlIVm1SVHFDdlNQQXZmUHZrVXg4SFE3ak91SWxzbGxTMXoKR1dUc2hHZVpwSU1uQTJaSm9FMDVVY0FIQjVNSjV3L095ODltMEdqcFFjellzZXpteGV2VituKzF2NHBFMlVzUQpZcjdySkFDRnhEQ0lxSFFJaEg0TGRZMHE5RkkzQmUvWE01Tmdja1lTcWFjM1JNZ0I1bjliaFFzUzNJWWxyZlRICkVmemtHVk1iQWJDL25VWGhabm5oVUVidlFNVkFvT2d6T1h2QURGa0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRMEYKQUFPQ0FRRUFCVWZRVXFmc1BScmpHWlVlNHR4cDJ6NXloTjQ2RHdSdEhVYVUvaHVxdjVWa2VuMStLTkVPM0d2UQo5L2xQOFVyUUZCV3pCRWw1UEZHSVpmNG1lVlQ1M3lhVHMvUkY4aU1XNmkySWEwN096dlNEQkhvc1A2NHZqZVRGCmVZWm1qQ3dqbTFmNllnRGRFc09BdGlPTlVsS3I5RDNNcUNWSXdialRzVXF1cHU2a28xVmw5T1UxVjc5WVIzaWoKOWVsWHV5YzdOL0ZhSkVRZTh1NkJ3YXpTNmtzdzhJNTRhM0JiKzhTVC8ya1lBVy80K3JLQXAzNVFpSE5yOWxqMwpnaVg1cDlPUUhQWDlEQjJzdnJmdEJoVi9HM2J0ZTY4YmFueStpT0Vkd044UGh3L2NLaVZlSlhTLzVCV01kZnd0CmZpc0UwWUVqQ0RqY0ZlOUk2R2ppY0xmSzU5K2tpQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
