---
apiVersion: v1
kind: Service
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: validating-admission 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  replicas: 1
  template:
    metadata:
      name: validating-admission 
      labels:
        name: validating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/validating-admission:1.0.0
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: validating-admission-cert
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-admission
webhooks:
  - name: validating-admission.qaware.de
    clientConfig:
      service:
        name: validating-admission
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVvQ0NRRFpiTnZmQ1dqaGh6QU5CZ2txaGtpRzl3MEJBUTBGQURDQndqRUxNQWtHQTFVRUJoTUMKUkVVeEVEQU9CZ05WQkFnTUIwSmhkbUZ5YVdFeEVqQVFCZ05WQkFjTUNWSnZjMlZ1YUdWcGJURU9NQXdHQTFVRQpFUXdGT0RNd01qSXhIakFjQmdOVkJBa01GVUp5dzRQQ3ZHTnJaVzV6ZEhKaHc0UENuMlVnTVRFVU1CSUdBMVVFCkNnd0xVVUYzWVhKbElFZHRZa2d4RGpBTUJnTlZCQXNNQlVkQ0xVMU1NUkl3RUFZRFZRUUREQWx4WVhkaGNtVXUKWkdVeEl6QWhCZ2txaGtpRzl3MEJDUUVXRkhGaGQyRnlaUzF2YzNOQWNXRjNZWEpsTG1SbE1CNFhEVEl4TURFeQpNakl3TkRVeU9Wb1hEVEl4TURJeU1USXdORFV5T1Zvd2djSXhDekFKQmdOVkJBWVRBa1JGTVJBd0RnWURWUVFJCkRBZENZWFpoY21saE1SSXdFQVlEVlFRSERBbFNiM05sYm1obGFXMHhEakFNQmdOVkJCRU1CVGd6TURJeU1SNHcKSEFZRFZRUUpEQlZDY3NPRHdyeGphMlZ1YzNSeVljT0R3cDlsSURFeEZEQVNCZ05WQkFvTUMxRkJkMkZ5WlNCSApiV0pJTVE0d0RBWURWUVFMREFWSFFpMU5UREVTTUJBR0ExVUVBd3dKY1dGM1lYSmxMbVJsTVNNd0lRWUpLb1pJCmh2Y05BUWtCRmhSeFlYZGhjbVV0YjNOelFIRmhkMkZ5WlM1a1pUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMMldHdHQ1SXJ6cUw0NGl3SEs1TS90cUZpYVAydmZBZGhhcG9GVUhxNnJMb0dzcQp2bG1tQUNFdGlMSHMvRHNCcC8vYmR4MXJJWU53eFM2bmQzQmh1NEJmbEdvSTlaV0dNRkRZYi8wTHFDN2pqRG1aCmlXL0lUYzNvTjBGd1VqaGRlN0FDUFJyY21NbmUyNDVBTlBEdW5RanRNK1ZlRE5GVDlFbVBFeEpNNGpic2ZLV0EKbEFUdkdhUVBQQUlYaDdNUko5NW40RWNoZmtKRUhJYUg4NEVZRFA0dnJtY2tnZmVRMkNaM29YSmNrK213d0dBRQphZjEwT1Zpc2JlN2F4UzJ0VDlhenhYNGxXQUN4czJtaGN1SFFsMnlZR0h3WXRua2xaMG5TY25kV2xpMnc2USsrClNIclBxU2s5Y0I2V2Y0dVF4RjZNYWhuN2tyUys4UEM5TXNjYjltOENBd0VBQVRBTkJna3Foa2lHOXcwQkFRMEYKQUFPQ0FRRUFUZlBibjBxd01KZVpEK1cvSHFLWUVvVXR3S2d3eHFxbmp5Z0pKVnJxd0N2T0pJSDVEL1pMTHF2dwpJZG10TXRKV2FtRjdaWE81UlVQZXovNHorQ09JMHBvOEdvMmJqejQzZkUrL3greEtDU0dObWtUNUxld2ZIUGZhCkpvUGRhTjBLOU43MWF5MlFMRFZjVUxFajVaZ21rdzRyZ3Jyc25WbFFDcFVrNWttZE80Nmdzb1VNY0hUV2dHVU0KWXlJYTdVc2VRNkUzeHRBcVJ3TGR0QmM2RGlBMkJ2Q0NCTHhEa1Q4NXRlUzBCTEhReW1UNlQwUTFHeDFHWDc5WQprRE81VWZjOVpWQm9UZ2MrSk1VYjdWTldqVkJDNk5JRjFNN2lad2RZcTN3TEJ3cUlSMTVpbHMvL3NFQ3VldWVnCmNnU05nOWNVOWR5cThmR2pzQVZoQ1l3Uml6RlBEdz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
