---
apiVersion: v1
kind: Service
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: validating-admission 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      name: validating-admission
  template:
    metadata:
      name: validating-admission 
      labels:
        name: validating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/validating-admission:latest
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 100Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: validating-admission-cert
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-admission.default.svc
webhooks:
  - name: validating-admission.default.svc
    clientConfig:
      service:
        name: validating-admission
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUQrakNDQXVJQ0NRRGRTbWx6ZGMzbHFUQU5CZ2txaGtpRzl3MEJBUTBGQURDQnZqRUxNQWtHQTFVRUJoTUMKUkVVeEVEQU9CZ05WQkFnTUIwSmhkbUZ5YVdFeEVqQVFCZ05WQkFjTUNWSnZjMlZ1YUdWcGJURU9NQXdHQTFVRQpFUXdGT0RNd01qSXhHakFZQmdOVkJBa01FVUp5ZFdWamEyVnVjM1J5WVhOelpTQXhNUlF3RWdZRFZRUUtEQXRSClFYZGhjbVVnUjIxaVNERU9NQXdHQTFVRUN3d0ZSMElnVFV3eEVqQVFCZ05WQkFNTUNYRmhkMkZ5WlM1a1pURWoKTUNFR0NTcUdTSWIzRFFFSkFSWVVjV0YzWVhKbExXOXpjMEJ4WVhkaGNtVXVaR1V3SGhjTk1qRXdNVEl5TWpFMApPVEEzV2hjTk1qRXdNakl4TWpFME9UQTNXakNCdmpFTE1Ba0dBMVVFQmhNQ1JFVXhFREFPQmdOVkJBZ01CMEpoCmRtRnlhV0V4RWpBUUJnTlZCQWNNQ1ZKdmMyVnVhR1ZwYlRFT01Bd0dBMVVFRVF3Rk9ETXdNakl4R2pBWUJnTlYKQkFrTUVVSnlkV1ZqYTJWdWMzUnlZWE56WlNBeE1SUXdFZ1lEVlFRS0RBdFJRWGRoY21VZ1IyMWlTREVPTUF3RwpBMVVFQ3d3RlIwSWdUVXd4RWpBUUJnTlZCQU1NQ1hGaGQyRnlaUzVrWlRFak1DRUdDU3FHU0liM0RRRUpBUllVCmNXRjNZWEpsTFc5emMwQnhZWGRoY21VdVpHVXdnZ0VpTUEwR0NTcUdTSWIzRFFFQkFRVUFBNElCRHdBd2dnRUsKQW9JQkFRQ2pNRFJpYWZNL1dZaTNoQ2VtSUpobjRuS1hHSFVtNlpSS0FDYjdMRFpVSUUyczZ3OThhQjBabnk4MQpGREcyS25SUERGMlFUbmtqU3VEVDB6RjB5NVNjWEhmK2pCdThudHcwbkV6Q05WazZiYmt5aTQ3RmNlNGlqNXBvCllUWml5MEVxQXhmRGU2U3BMTlg0WHhDL2FqVCszVVNDM2pVMWFIOXE3Y0hHYjhTYkVCWTlsUEhkVElVUzhRbWkKSnVwOFpZOVV5QlF0YW9Cbkg4WCtDMGt5RmxLalhtOU1IaFRnQlpsWDdFcHpKTU1pQjB0VHdzLzlZditLNEVNdwpHa1JoY2tmbi9CMjF4U2JwUFdxZTFUSWc2eXJJSndUMkl5cHpBTzUyeU5vWGNVRHAranYvUWw4b2dPNktCMUNJCjFlR2xTNmRjMnBJem1kQ1Z5Z2ltaUNncUlKU0hBZ01CQUFFd0RRWUpLb1pJaHZjTkFRRU5CUUFEZ2dFQkFHWUMKd094ODduTzdHay9YWHBGN2ZtUHZmc3J6VVIvcFRNbzlXOVRTcnp6QUp1UG1ta2VzZ2pTSnM4ZE9NTlY3SlhrVgo3RnRrN25wU24xSTF0eGduU2Y1c0ZVbW5jQjFRQS9oMnFYdVZXalF5ZjE2NHdEVkxmWmkwRGkzTUdkVW92YTg4Cm9SZy9LY1dZS3JaSlhuZUFxOUpSV0VDL0pkQXBibUQ5TlMwazZlYmRmblV1cFVlRVdVMXZkL0JhcU56Zk5JcDcKaXBEVU9BOUNVbjUzWlNGUldOaEpKb09YcDY4NHI4OVN6VDVobUR3SVNxaW5VWFEvd3hYOUgxOFQwWlB3MHMrMQpzVnp2RlpJdzlGd3ptYTB0Zms1QVJTcTVFSTJKZHZWS1ZlZk1mY0NNZi9Na0xqWDZJVFU2ZU5IWDNyQitFWW5mCjR0SVZtRjE5T0c3WDlzUGJCN0E9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10