apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus-setup
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  path: ./manifests/setup
  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: kube-prometheus
  namespace: flux-system
spec:
  interval: 5m0s
  dependsOn:
    - name: kube-prometheus-setup
  sourceRef:
    kind: GitRepository
    name: kube-prometheus
  path: ./manifests
  prune: true
  validation: client