apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutating-admission-deployment
  labels:
    app: mutating-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutating-admission
  template:
    metadata:
      labels:
        app: mutating-admission
    spec:
      containers:
      - name: mutating-admission
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: mutating-admission-tls-secret
          mountPath: "/tls"
          readOnly: true        
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"           
        imagePullPolicy: Always
      volumes:
      - name: mutating-admission-tls-secret
        secret:
          secretName: mutating-admission-tls-secret