apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- webhook.yaml
images:
- name: CONTAINER_IMAGE
  newName: lreimer/mutating-admission
  newTag: 1.0.2
