apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="de">
    <head>
        <title>Kubernetes Experts Day Microservice Demo</title>
    </head>
    <body>
        <h1>Kubernetes Experts Day Microservice Demo</h1>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
    environment: integration
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    killpod/enabled: "true"
    killpod/application: nginx
    killpod/delay: "30"
    killpod/amount: "1"
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
        environment: integration
        killpod/application: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.19.4-alpine
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html-files
            readOnly: true
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html-files
          configMap:
            name: nginx-configmap
            items:
              - key: index.html
                path: index.html