---
apiVersion: v1
kind: Service
metadata:
  name: mutating-admission
  namespace: default
  labels:
    name: mutating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: mutating-admission 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mutating-admission
  namespace: default
  labels:
    name: mutating-admission
spec:
  replicas: 1
  template:
    metadata:
      name: mutating-admission 
      labels:
        name: mutating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/mutating-admission:1.0.0
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: mutating-admission-cert
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission
webhooks:
  - name: mutating-admission.qaware.de
    clientConfig:
      service:
        name: mutating-admission
        namespace: default
        path: "/validate"
      caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVBakNDQXVvQ0NRRHB4SlliaDlxT0pUQU5CZ2txaGtpRzl3MEJBUTBGQURDQndqRUxNQWtHQTFVRUJoTUMKUkVVeEVEQU9CZ05WQkFnTUIwSmhkbUZ5YVdFeEVqQVFCZ05WQkFjTUNWSnZjMlZ1YUdWcGJURU9NQXdHQTFVRQpFUXdGT0RNd01qSXhIakFjQmdOVkJBa01GVUp5dzRQQ3ZHTnJaVzV6ZEhKaHc0UENuMlVnTVRFVU1CSUdBMVVFCkNnd0xVVUYzWVhKbElFZHRZa2d4RGpBTUJnTlZCQXNNQlVkQ0xVMU1NUkl3RUFZRFZRUUREQWx4WVhkaGNtVXUKWkdVeEl6QWhCZ2txaGtpRzl3MEJDUUVXRkhGaGQyRnlaUzF2YzNOQWNXRjNZWEpsTG1SbE1CNFhEVEl4TURFeQpNakl3TkRZd01Wb1hEVEl4TURJeU1USXdORFl3TVZvd2djSXhDekFKQmdOVkJBWVRBa1JGTVJBd0RnWURWUVFJCkRBZENZWFpoY21saE1SSXdFQVlEVlFRSERBbFNiM05sYm1obGFXMHhEakFNQmdOVkJCRU1CVGd6TURJeU1SNHcKSEFZRFZRUUpEQlZDY3NPRHdyeGphMlZ1YzNSeVljT0R3cDlsSURFeEZEQVNCZ05WQkFvTUMxRkJkMkZ5WlNCSApiV0pJTVE0d0RBWURWUVFMREFWSFFpMU5UREVTTUJBR0ExVUVBd3dKY1dGM1lYSmxMbVJsTVNNd0lRWUpLb1pJCmh2Y05BUWtCRmhSeFlYZGhjbVV0YjNOelFIRmhkMkZ5WlM1a1pUQ0NBU0l3RFFZSktvWklodmNOQVFFQkJRQUQKZ2dFUEFEQ0NBUW9DZ2dFQkFMNVZOeXpVVExaVkZQOEh0d3lCQmZDQzRFdVJEUTVFdFI3aEFwOUZ3RXF3ZVljNwpScVpwTjVyVVhvc3JuNUtyblh5aURLdWd3Nm5udUxXNFJUdndHZlVPZU4zSzc0UDI3T3lrcnNuS0VMOXBnNWNqCng2OElxeFhITjZRMzlZbEU3bjk2OUM4YnZ3cU5LRTU4RGo2SWZLM3phQWRoZG1vdDhDQkxscnJIbkpUQTZIU0wKYURKYkNtdmVpQ25QQnF6b05BQmFQbElsNi9MZXFNM1BCQUIrRkRma3FLVnFQVHpRdi94OVVQa2NTemJPWE5zVQpsQ0RkTnEvc0J1a2RCTmY4dUFoTjBnSTZMb1VLSXFreHRLRnJXaU1wTllqdWNXSkdsU2NBMDBERDBubG8rVENWCjdsa3VSdmFCN0hpaURYNXgrVzhHYWxmRURWNjZMZ2YvL3d2RVo2Y0NBd0VBQVRBTkJna3Foa2lHOXcwQkFRMEYKQUFPQ0FRRUFCTGlOeU5PN1VTaFo3eVlQVU5RSEJSaVRpTkVIenhxM2RWdUM1UEo2UmIvMGdMQ0J2OUJGdTEyeQo1RTUzbDdzcFV6RXBtSzZRNEt4bDFjeUlHc2hYYkVOT2pzVVRXMWVFSHIvWGtGa05QTXR2a3VhQkprR0c2U2prCk1FQ1k2alVXWDRUN3JZazJwMzNSeUxrUmtZZlRrZVRHL1pRMXJ0Z2hqb1lPYzVOZVBvTlJVdDBXN1IycTRCNHcKN3BmYXFkcHFLMFhEa2dhSjZBM2RHOUlVdlNSRnZtZnY4cUZuME9rdnRTdmhXaDk1elI2VTQ4cjF4NnA0WW05UQpRczNyMDhjZ0Y3ejFVY3FhNHl5bkRIZVVnNDFoTjdjdTUwYmx5SDcyd2dnRmFTTmc0S3BJWjdBajVQdmNYNkk3CnZaWkVYOVVnVGcwYmdmUFpXNUdEbjdkRHBQTXlHQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
