apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: validating-admission-webhook-cert-cluster-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: validating-admission-webhook-cert-cluster-role
subjects:
  - kind: ServiceAccount
    name: validating-admission-webhook-cert-sa
    namespace: default
