---
apiVersion: v1
kind: Service
metadata:
  name: mutating-admission
  namespace: default
  labels:
    name: mutating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: mutating-admission 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mutating-admission
  namespace: default
  labels:
    name: mutating-admission
spec:
  replicas: 1
  template:
    metadata:
      name: mutating-admission 
      labels:
        name: mutating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/mutating-admission:1.0.0
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 50Mi
              cpu: 300m
            requests:
              memory: 100Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: mutating-admission
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-admission
webhooks:
  - name: mutating-admission.qaware.de
    clientConfig:
      service:
        name: mutating-admission
        namespace: default
        path: "/validate"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
