apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
    type: microservice
spec:
  containers:
  - name: nginx
    image: nginx:1.19.4-alpine
    ports:
      - containerPort: 80
    readinessProbe:
      initialDelaySeconds: 1
      timeoutSeconds: 1
      periodSeconds: 5
      httpGet:
        port: 80
        path: /
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      periodSeconds: 10
      httpGet:
        port: 80
        path: /