apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: {{ .Params.serviceType }}
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: nginx
    environment: integration