apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  environment: integration

namePrefix: int-

bases:
  # you can also specify a Git repo URL here
  - ../../base

patchesStrategicMerge:
  - 2-replicas.yaml
  - loadbalancer.yaml

configMapGenerator:
  - name: nginx-configmap
    behavior: merge
    files:
      - index.html
    literals:
      - HOST=integration.qaware.de
      - PORT=80