apiVersion: v1
kind: Service
metadata:
  name: validating-admission-service
spec:
  type: ClusterIP
  selector:
    app: validating-admission
  ports:
  - protocol: TCP
    port: 443
    targetPort: 8000
