apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 30s
  url: https://github.com/stefanprodan/podinfo
  ref:
    tag: 6.0.0