---
apiVersion: v1
kind: Service
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  ports:
  - name: webhook
    port: 443
    targetPort: 8080
  selector:
    name: validating-admission 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validating-admission
  namespace: default
  labels:
    name: validating-admission
spec:
  replicas: 1
  selector:
    matchLabels:
      name: validating-admission
  template:
    metadata:
      name: validating-admission 
      labels:
        name: validating-admission
    spec:
      containers:
        - name: webhook
          image: lreimer/validating-admission:latest
          imagePullPolicy: Always
          args:
            - -alsologtostderr
            - --log_dir=/
            - -v=10
            - 2>&1
          resources:
            limits:
              memory: 100Mi
              cpu: 300m
            requests:
              memory: 50Mi
              cpu: 300m
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/certs
              readOnly: true
            - name: logs
              mountPath: /tmp
          securityContext:
            readOnlyRootFilesystem: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: validating-admission-cert
        - name: logs
          emptyDir: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-admission.default.svc
webhooks:
  - name: validating-admission.default.svc
    clientConfig:
      service:
        name: validating-admission
        namespace: default
        path: "/validate"
      caBundle: "${CA_BUNDLE}"
    rules:
      - operations: ["CREATE","UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    failurePolicy: Ignore
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
    timeoutSeconds: 10