apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: nginx

namespace: default
nameSuffix: -v1

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: nginx-configmap    
    files:
      - favicon.ico
    literals:
      - HOST=localhost
      - PORT=8080